 # from services.user_service import UserService

def index():
    return {"message": "User found"}, 201
def store():
    ...
def show(userId):
    ...
def update(userId):
    ...
def destroy(userId):
    ...